### ISSUE TITLE
Calculation doesn't work when getRisk returns "Critical"

### ISSUE THREAD

**Issue by johnebgood** [Ivan-Markovic/OWASP-Risk-Assessment-Calculator#1]
The likelihood row class names only contain "Low", "Medium" and "High", when "Critical" is returned the title row is selected. I hacked in some fixes in a fork that also adds better final table indicators and overall risk calculation.

**Comment by Ivan-Markovic** [comment]
Thank you, quick fix is implemented. I need to rewrite whole script.
