### ISSUE TITLE
Skill rating is inversed

### ISSUE THREAD

**Issue by Gunstick** [Ivan-Markovic/OWASP-Risk-Assessment-Calculator#2]
After the Wiki edit war at OWASP, you got the wrong ratings for 'skill level'. The list is in fact the other way around.
Here is the current article: https://wiki.owasp.org/index.php/OWASP_Risk_Rating_Methodology#Threat_Agent_Factors
And the discussion arguing why "no skill"=1 and not 9 https://wiki.owasp.org/index.php/Talk:OWASP_Risk_Rating_Methodology

**Comment by pmilosev** [comment]
I just came to report the same issue. This is a common mistake. Skill level here is not what is required (that would then be a vulnerability factor), but how skilled is your modeled adversary.

**Comment by Ivan-Markovic** [comment]
Thank you, quick fix is implemented. I need to rewrite whole script.
